### ISSUE TITLE
/localisation having UTF-8 encoding

### ISSUE THREAD

**Issue by Aerotinge** [LaTueur/CK2-Community-Patch#1]
It seems localisation csv file is saved as UTF-8 encoding.
I open them with ISO 8859-15 and it goes like.
![UTF-8_ANSI](https://user-images.githubusercontent.com/6275647/68385785-7e5cfe80-0195-11ea-84db-c57ba5de6d82.png)
As Git, I've my default content encoding set as ISO-8859-1.
And IIRC non UTF-8 characters are supposed to be rendered incorrectly on Github.
(Should we simply goes to UTF-8 for git and convert manually when exporting to a mod?)

**Comment by LaTueur** [comment]
Ah, I forgot it. Thanks for the fix.
